name: Terraform (infra)

on:
  # Apply only after merge to main
  push:
    branches: [ "main" ]
    paths:
      - "infra/**"
      - ".github/workflows/deploy-infra.yml"
  # PRs run fmt/validate only (no Azure login)
  pull_request:
    branches: [ "main" ]
    paths:
      - "infra/**"
      - ".github/workflows/deploy-infra.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: infra-terraform
  cancel-in-progress: true

env:
  TF_IN_AUTOMATION: 'true'
  WORKING_DIR: 'infra'

jobs:
  validate:
    # PR-only job: no Azure login to avoid AADSTS700213
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform fmt
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform fmt -check

      # Validate without hitting remote backend (works offline on PRs)
      - name: Terraform init (no backend)
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform validate

  apply:
    # Only apply on push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC via tf-deployer)
        uses: azure/login@v2
        with:
          client-id:   "bdbc6bec-6f3d-48b9-99e9-6bbcc0ef51f5"        # tf-deployer app (client) ID 
          tenant-id:   "6dd7381d-4ace-410a-b7f3-011a192ebe60"       # your tenant ID
          subscription-id:  "c1b1f12b-41c7-4fb3-b5ac-02e36ce1331e"   # your subscription ID

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform apply -auto-approve
