name: Deploy Azure Function

on:
  push:
    branches: [ "main" ]
    paths: [ "function/**", ".github/workflows/deploy-function.yml" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: afemailsjs-func   # or load from TF outputs via env or artifacts
  NODE_VERSION: '20.x'
  WORKING_DIR: 'function'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIR }}/package-lock.json

      - name: Install deps
        working-directory: ${{ env.WORKING_DIR }}
        run: npm ci

      # (Optional) tests
      # - name: Test
      #   working-directory: ${{ env.WORKING_DIR }}
      #   run: npm test --if-present

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.WORKING_DIR }}
